const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

function hash(filePath) {
  if (!fs.existsSync(filePath)) return null;
  const content = fs.readFileSync(filePath);
  return crypto.createHash('md5').update(content).digest('hex').slice(0, 8);
}

// 1. Minify CSS and JS
console.log('Minifying CSS...');
execSync('npx clean-css-cli -o css/style.min.css css/style.css', { stdio: 'inherit' });

console.log('Minifying JS...');
execSync('npx terser js/main.js -o js/main.min.js -c -m', { stdio: 'inherit' });

// 2. Build hash map for all assets referenced in index.html
const assetDirs = ['css', 'js', 'assets', 'assets/portfolio'];
const extensions = ['.css', '.js', '.webp', '.png', '.jpg', '.jpeg', '.svg'];

const hashMap = new Map();
for (const dir of assetDirs) {
  const fullDir = path.join(__dirname, dir);
  if (!fs.existsSync(fullDir)) continue;
  for (const file of fs.readdirSync(fullDir)) {
    if (!extensions.includes(path.extname(file).toLowerCase())) continue;
    const relPath = path.posix.join(dir, file);
    const h = hash(path.join(fullDir, file));
    if (h) hashMap.set(relPath, h);
  }
}

// 3. Read index.html and replace asset references
let html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');

for (const [assetPath, h] of hashMap) {
  const escaped = assetPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // Only bust relative references — skip absolute URLs (og:image, JSON-LD, etc.)
  const regex = new RegExp(`(["'])${escaped}(\\?v=[a-f0-9]+)?(["'])`, 'g');
  html = html.replace(regex, (match, q1, _old, q2, offset) => {
    const before = html.slice(Math.max(0, offset - 80), offset);
    if (/https?:\/\//.test(before)) return match;
    return `${q1}${assetPath}?v=${h}${q2}`;
  });

  // srcset references (always relative)
  const srcsetRegex = new RegExp(`(srcset=["'][^"']*?)(${escaped})(\\?v=[a-f0-9]+)?`, 'g');
  html = html.replace(srcsetRegex, `$1$2?v=${h}`);
}

fs.writeFileSync(path.join(__dirname, 'index.html'), html, 'utf8');

console.log('\nCache-busted assets:');
for (const [p, h] of hashMap) console.log(`  ${p}?v=${h}`);

// 4. Auto-update xhs.html featured blog card with the latest blog post
console.log('\nUpdating xhs.html featured blog...');

function extractMeta(content, property) {
  const re = new RegExp(`<meta\\s+property=["']${property}["']\\s+content=["']([^"']+)["']`);
  const m = content.match(re);
  return m ? m[1] : null;
}

const blogDir = path.join(__dirname, 'blog');
const blogFiles = fs.readdirSync(blogDir)
  .filter(f => f.endsWith('.html') && f !== 'index.html');

const blogs = blogFiles.map(filename => {
  const content = fs.readFileSync(path.join(blogDir, filename), 'utf8');
  return {
    filename,
    date: extractMeta(content, 'article:published_time'),
    title: extractMeta(content, 'og:title'),
    description: extractMeta(content, 'og:description'),
  };
}).filter(b => b.date && b.title && b.description);

if (blogs.length === 0) {
  console.log('  No blog posts with article:published_time found, skipping.');
} else {
  blogs.sort((a, b) => new Date(b.date) - new Date(a.date));
  const latest = blogs[0];

  const [y, m, d] = latest.date.split('-');
  const dateFormatted = `${y}.${parseInt(m, 10)}.${parseInt(d, 10)}`;
  const url = `blog/${latest.filename}?utm_source=xiaohongshu&utm_medium=bio&utm_campaign=xhs_landing`;

  const featuredHtml = `<!-- XHS:FEATURED:START — auto-generated by build.js, do not edit by hand -->
        <a href="${url}"
           class="blog-feature-card"
           onclick="gtag('event','click',{event_category:'XHS Landing',event_label:'Featured Blog Card'})">
          <span class="blog-card-tag">📝 BLOG · 必读</span>
          <h3>${latest.title}</h3>
          <p>${latest.description}</p>
          <div class="blog-card-meta">
            <span>📅 ${dateFormatted}</span>
            <span class="read-arrow">读全文 →</span>
          </div>
        </a>
        <!-- XHS:FEATURED:END -->`;

  const xhsPath = path.join(__dirname, 'xhs.html');
  let xhsHtml = fs.readFileSync(xhsPath, 'utf8');
  const markerRe = /<!-- XHS:FEATURED:START[\s\S]*?XHS:FEATURED:END -->/;

  if (!markerRe.test(xhsHtml)) {
    console.log('  ⚠ xhs.html missing XHS:FEATURED markers, skipping update.');
  } else {
    xhsHtml = xhsHtml.replace(markerRe, featuredHtml);
    fs.writeFileSync(xhsPath, xhsHtml, 'utf8');
    console.log(`  ✓ Featured blog → ${latest.filename}  (${latest.date})`);
  }
}

console.log('\nDone!');
